### ISSUE TITLE
Any Icon?

### ISSUE THREAD

**Issue by nrudesu** [GNUWeeb/gnuweeb.github.io#2]
Since website have no icons, we need for add those. but after #1 solved.

- [x] Add icon
- [x] Ensure that icon shows

**Comment by Sprtcrnbry** [comment]
![image](https://user-images.githubusercontent.com/17063780/116260968-6326ea00-a7a1-11eb-9d4c-0b1e06bcd220.png)
icon shows up on both firefox and chromium

**Comment by Sprtcrnbry** [comment]
i have added the code for it a few days ago, it is in the current code in the repo

**Comment by nrudesu** [comment]
okay nice, let's close this issue
